# Generated by Django 3.2 on 2021-04-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
