# Generated by Django 3.2 on 2021-04-26 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('news', '0002_alter_newsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='categories.categorymodel'),
        ),
    ]
